In [6]:
import numpy as np

### THE Basics

In [7]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]], dtype='float64')
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
#get dimension
b.ndim

2

In [10]:
a.ndim

1

In [11]:
b.shape

(2, 3)

In [12]:
a.shape

(3,)

In [13]:
a.dtype

dtype('int32')

In [14]:
b.dtype

dtype('float64')

In [15]:
a.itemsize

4

In [16]:
b.itemsize

8

In [17]:
#b.size * b.itemsize = nbytes
b.nbytes

48

In [18]:
b.size

6

In [19]:
a.size

3

###### Accessing/changing specific elements, rows,columns,etc

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
# get a specific element[r, c]
a[-1, -2]

13

In [27]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
# get a specific column
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
# [start:end:step]
a[0, 1:-1:2]

array([2, 4, 6])

In [53]:
a[1,5]=20
print(a)

a[1, :]=[0,9,8,7,6,5,4]
print(a)

[[ 1  2  0  4  5  6  7]
 [20 20 20 20 20 20 20]]
[[1 2 0 4 5 6 7]
 [0 9 8 7 6 5 4]]


#          3-d example

In [58]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [94]:
# get specific element
b[1,0,0]

5

In [102]:
#  replace 
b[:,1,:] = [[6,6],[9,9]]
print(b)

[[[1 2]
  [6 6]]

 [[5 6]
  [9 9]]]


In [123]:
np.random.randint(8, size=(2,2))

array([[6, 3],
       [4, 7]])

# mathematics

In [149]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [152]:
print(a + 2)

[3 4 5 6]


In [153]:
a - 2

array([-1,  0,  1,  2])

In [127]:
a * 2

array([2, 4, 6, 8])

In [128]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [155]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [157]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])